[build-system]
requires = "python >= 3.8"

[project]
name = "rainbow"
version = "1.0.0"

[dependencies]
sense_hat = "^4.1.0"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = "python >= 3.8"
